title: "Marçal Evangelista"
email: "marcal@iaa.es"
description: >-
  Personal academic website of Marçal Evangelista, astrophysicist specialized in cometary science,
  small Solar System bodies, and planetary system formation. This site includes publications, projects,
  code, outreach, and contact.

minimal_mistakes_skin: "air"
search: true
locale: "en-US"

url: "https://marcalevangelista.github.io"
baseurl: ""

author:
  name   : "Marçal Evangelista"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Astrophysicist | Comets, Dust, and Small Bodies | Postdoc at IAA-CSIC"
  location: "Granada, Spain"
  links:
    - label: "Lattes"
      icon: "fas fa-fw fa-id-card"
      url: "https://lattes.cnpq.br/9028132638049706"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-1153-8768"
    - label: "ADS"
      icon: "fas fa-fw fa-book"
      url: "https://ui.adsabs.harvard.edu/user/libraries/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarcalEvangelista"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:marcal@astro.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarcalEvangelista"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-1153-8768"
    - label: "ADS"
      icon: "fas fa-fw fa-book"
      url: "https://ui.adsabs.harvard.edu/"

# Navigation bar
navigation:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

paginate: 5
paginate_path: "/page:num/"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

