name: Atualizar publicações do ADS

on:
  schedule:
    - cron: '0 6 * * 1'  # Toda segunda-feira às 06:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests pyyaml

      - name: Rodar script de atualização
        run: python script/update_publications.py
        env:
          ADS_TOKEN: ${{ secrets.ADS_TOKEN }}

      - name: Confirmar alterações no Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add _data/publications.yml
          git commit -m "Atualizar publicações automaticamente via ADS" || echo "Sem mudanças"
          git push

